/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralRouteImport } from './routes/central'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as IniciativasRouteImport } from './routes/iniciativas'
import { Route as CentralEntregasRouteImport } from './routes/central_.entregas'
import { Route as CentralOrgaosRouteImport } from './routes/central_.orgaos'
import { Route as CentralProgramasRouteImport } from './routes/central_.programas'
import { Route as EntregaIdRouteImport } from './routes/entrega.$id'
import { Route as IniciativaIdRouteImport } from './routes/iniciativa.$id'
import { Route as ProgramaIdRouteImport } from './routes/programa.$id'
import { Route as CentralAnalisesCausasRouteImport } from './routes/central_.analises.causas'
import { Route as CentralAnalisesFinanceiraRouteImport } from './routes/central_.analises.financeira'
import { Route as CentralAnalisesIpofsRouteImport } from './routes/central_.analises.ipofs'
import { Route as CentralAnalisesProjetosRouteImport } from './routes/central_.analises.projetos'
import { Route as CentralIniciativaIdRouteImport } from './routes/central_.iniciativa.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciativasRoute = IniciativasRouteImport.update({
  id: '/iniciativas',
  path: '/iniciativas',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralEntregasRoute = CentralEntregasRouteImport.update({
  id: '/central_/entregas',
  path: '/central/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralOrgaosRoute = CentralOrgaosRouteImport.update({
  id: '/central_/orgaos',
  path: '/central/orgaos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralProgramasRoute = CentralProgramasRouteImport.update({
  id: '/central_/programas',
  path: '/central/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaIdRoute = EntregaIdRouteImport.update({
  id: '/entrega/$id',
  path: '/entrega/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciativaIdRoute = IniciativaIdRouteImport.update({
  id: '/iniciativa/$id',
  path: '/iniciativa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaIdRoute = ProgramaIdRouteImport.update({
  id: '/programa/$id',
  path: '/programa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAnalisesCausasRoute = CentralAnalisesCausasRouteImport.update({
  id: '/central_/analises/causas',
  path: '/central/analises/causas',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAnalisesFinanceiraRoute =
  CentralAnalisesFinanceiraRouteImport.update({
    id: '/central_/analises/financeira',
    path: '/central/analises/financeira',
    getParentRoute: () => rootRouteImport,
  } as any)
const CentralAnalisesIpofsRoute = CentralAnalisesIpofsRouteImport.update({
  id: '/central_/analises/ipofs',
  path: '/central/analises/ipofs',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAnalisesProjetosRoute = CentralAnalisesProjetosRouteImport.update({
  id: '/central_/analises/projetos',
  path: '/central/analises/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIniciativaIdRoute = CentralIniciativaIdRouteImport.update({
  id: '/central_/iniciativa/$id',
  path: '/central/iniciativa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/entregas': typeof EntregasRoute
  '/indicadores': typeof IndicadoresRoute
  '/iniciativas': typeof IniciativasRoute
  '/central/entregas': typeof CentralEntregasRoute
  '/central/orgaos': typeof CentralOrgaosRoute
  '/central/programas': typeof CentralProgramasRoute
  '/entrega/$id': typeof EntregaIdRoute
  '/iniciativa/$id': typeof IniciativaIdRoute
  '/programa/$id': typeof ProgramaIdRoute
  '/central/analises/causas': typeof CentralAnalisesCausasRoute
  '/central/analises/financeira': typeof CentralAnalisesFinanceiraRoute
  '/central/analises/ipofs': typeof CentralAnalisesIpofsRoute
  '/central/analises/projetos': typeof CentralAnalisesProjetosRoute
  '/central/iniciativa/$id': typeof CentralIniciativaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/entregas': typeof EntregasRoute
  '/indicadores': typeof IndicadoresRoute
  '/iniciativas': typeof IniciativasRoute
  '/central/entregas': typeof CentralEntregasRoute
  '/central/orgaos': typeof CentralOrgaosRoute
  '/central/programas': typeof CentralProgramasRoute
  '/entrega/$id': typeof EntregaIdRoute
  '/iniciativa/$id': typeof IniciativaIdRoute
  '/programa/$id': typeof ProgramaIdRoute
  '/central/analises/causas': typeof CentralAnalisesCausasRoute
  '/central/analises/financeira': typeof CentralAnalisesFinanceiraRoute
  '/central/analises/ipofs': typeof CentralAnalisesIpofsRoute
  '/central/analises/projetos': typeof CentralAnalisesProjetosRoute
  '/central/iniciativa/$id': typeof CentralIniciativaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/entregas': typeof EntregasRoute
  '/indicadores': typeof IndicadoresRoute
  '/iniciativas': typeof IniciativasRoute
  '/central_/entregas': typeof CentralEntregasRoute
  '/central_/orgaos': typeof CentralOrgaosRoute
  '/central_/programas': typeof CentralProgramasRoute
  '/entrega/$id': typeof EntregaIdRoute
  '/iniciativa/$id': typeof IniciativaIdRoute
  '/programa/$id': typeof ProgramaIdRoute
  '/central_/analises/causas': typeof CentralAnalisesCausasRoute
  '/central_/analises/financeira': typeof CentralAnalisesFinanceiraRoute
  '/central_/analises/ipofs': typeof CentralAnalisesIpofsRoute
  '/central_/analises/projetos': typeof CentralAnalisesProjetosRoute
  '/central_/iniciativa/$id': typeof CentralIniciativaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/central'
    | '/entregas'
    | '/indicadores'
    | '/iniciativas'
    | '/central/entregas'
    | '/central/orgaos'
    | '/central/programas'
    | '/entrega/$id'
    | '/iniciativa/$id'
    | '/programa/$id'
    | '/central/analises/causas'
    | '/central/analises/financeira'
    | '/central/analises/ipofs'
    | '/central/analises/projetos'
    | '/central/iniciativa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/central'
    | '/entregas'
    | '/indicadores'
    | '/iniciativas'
    | '/central/entregas'
    | '/central/orgaos'
    | '/central/programas'
    | '/entrega/$id'
    | '/iniciativa/$id'
    | '/programa/$id'
    | '/central/analises/causas'
    | '/central/analises/financeira'
    | '/central/analises/ipofs'
    | '/central/analises/projetos'
    | '/central/iniciativa/$id'
  id:
    | '__root__'
    | '/'
    | '/central'
    | '/entregas'
    | '/indicadores'
    | '/iniciativas'
    | '/central_/entregas'
    | '/central_/orgaos'
    | '/central_/programas'
    | '/entrega/$id'
    | '/iniciativa/$id'
    | '/programa/$id'
    | '/central_/analises/causas'
    | '/central_/analises/financeira'
    | '/central_/analises/ipofs'
    | '/central_/analises/projetos'
    | '/central_/iniciativa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralRoute: typeof CentralRoute
  EntregasRoute: typeof EntregasRoute
  IndicadoresRoute: typeof IndicadoresRoute
  IniciativasRoute: typeof IniciativasRoute
  CentralEntregasRoute: typeof CentralEntregasRoute
  CentralOrgaosRoute: typeof CentralOrgaosRoute
  CentralProgramasRoute: typeof CentralProgramasRoute
  EntregaIdRoute: typeof EntregaIdRoute
  IniciativaIdRoute: typeof IniciativaIdRoute
  ProgramaIdRoute: typeof ProgramaIdRoute
  CentralAnalisesCausasRoute: typeof CentralAnalisesCausasRoute
  CentralAnalisesFinanceiraRoute: typeof CentralAnalisesFinanceiraRoute
  CentralAnalisesIpofsRoute: typeof CentralAnalisesIpofsRoute
  CentralAnalisesProjetosRoute: typeof CentralAnalisesProjetosRoute
  CentralIniciativaIdRoute: typeof CentralIniciativaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciativas': {
      id: '/iniciativas'
      path: '/iniciativas'
      fullPath: '/iniciativas'
      preLoaderRoute: typeof IniciativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/entregas': {
      id: '/central_/entregas'
      path: '/central/entregas'
      fullPath: '/central/entregas'
      preLoaderRoute: typeof CentralEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/orgaos': {
      id: '/central_/orgaos'
      path: '/central/orgaos'
      fullPath: '/central/orgaos'
      preLoaderRoute: typeof CentralOrgaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/programas': {
      id: '/central_/programas'
      path: '/central/programas'
      fullPath: '/central/programas'
      preLoaderRoute: typeof CentralProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$id': {
      id: '/entrega/$id'
      path: '/entrega/$id'
      fullPath: '/entrega/$id'
      preLoaderRoute: typeof EntregaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciativa/$id': {
      id: '/iniciativa/$id'
      path: '/iniciativa/$id'
      fullPath: '/iniciativa/$id'
      preLoaderRoute: typeof IniciativaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa/$id': {
      id: '/programa/$id'
      path: '/programa/$id'
      fullPath: '/programa/$id'
      preLoaderRoute: typeof ProgramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/analises/causas': {
      id: '/central_/analises/causas'
      path: '/central/analises/causas'
      fullPath: '/central/analises/causas'
      preLoaderRoute: typeof CentralAnalisesCausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/analises/financeira': {
      id: '/central_/analises/financeira'
      path: '/central/analises/financeira'
      fullPath: '/central/analises/financeira'
      preLoaderRoute: typeof CentralAnalisesFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/analises/ipofs': {
      id: '/central_/analises/ipofs'
      path: '/central/analises/ipofs'
      fullPath: '/central/analises/ipofs'
      preLoaderRoute: typeof CentralAnalisesIpofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/analises/projetos': {
      id: '/central_/analises/projetos'
      path: '/central/analises/projetos'
      fullPath: '/central/analises/projetos'
      preLoaderRoute: typeof CentralAnalisesProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central_/iniciativa/$id': {
      id: '/central_/iniciativa/$id'
      path: '/central/iniciativa/$id'
      fullPath: '/central/iniciativa/$id'
      preLoaderRoute: typeof CentralIniciativaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralRoute: CentralRoute,
  EntregasRoute: EntregasRoute,
  IndicadoresRoute: IndicadoresRoute,
  IniciativasRoute: IniciativasRoute,
  CentralEntregasRoute: CentralEntregasRoute,
  CentralOrgaosRoute: CentralOrgaosRoute,
  CentralProgramasRoute: CentralProgramasRoute,
  EntregaIdRoute: EntregaIdRoute,
  IniciativaIdRoute: IniciativaIdRoute,
  ProgramaIdRoute: ProgramaIdRoute,
  CentralAnalisesCausasRoute: CentralAnalisesCausasRoute,
  CentralAnalisesFinanceiraRoute: CentralAnalisesFinanceiraRoute,
  CentralAnalisesIpofsRoute: CentralAnalisesIpofsRoute,
  CentralAnalisesProjetosRoute: CentralAnalisesProjetosRoute,
  CentralIniciativaIdRoute: CentralIniciativaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
