import type {
  AcaoOrcamentaria,
  Comentario,
  Entrega,
  Evento,
  Iniciativa,
  Ipof,
  ParcelaIpof,
  PpaState,
  Programa,
  ProjetoGomap,
  Vinculo,
  VinculoAcao,
} from "./types";

export const ORGAOS = [
  "Secretaria de Desenvolvimento Social",
  "Secretaria de Saúde",
  "Secretaria de Educação",
  "Secretaria de Infraestrutura",
  "Secretaria de Agricultura",
  "Secretaria de Meio Ambiente",
  "Secretaria de Indústria e Comércio",
  "Secretaria de Segurança Pública",
];

export const PERIODICIDADES = ["Mensal", "Trimestral", "Semestral", "Anual"];

export const ANOS = ["2028", "2029", "2030", "2031"];

export const ORGAO_SETORIAL = "Secretaria de Desenvolvimento Social";

export const REGIOES = [
  "Metropolitana de Goiânia",
  "Entorno do DF",
  "Sudoeste Goiano",
  "Norte Goiano",
  "Nordeste Goiano",
  "Centro Goiano",
  "Sul Goiano",
];

export const UNIDADES = [
  "Unidade",
  "Pessoa atendida",
  "Município atendido",
  "Percentual",
  "Profissional capacitado",
  "Tonelada",
  "Refeição servida",
];

export const PROGRAMAS: Programa[] = [
  {
    id: "pg-saude",
    codigo: "001",
    nome: "Saúde Integral",
    eixo: "Goiás que cuida",
    objetivoEstrategico: "Ampliar o acesso qualificado à rede de atenção à saúde em todas as regiões.",
    problema:
      "Tempo de espera elevado para atendimento especializado e distribuição desigual da capacidade assistencial entre as regiões de saúde.",
    evidencias: [
      "Fila de regulação com 214 mil solicitações pendentes em 2026.",
      "4 das 7 macrorregiões abaixo do parâmetro de leitos de UTI por habitante.",
    ],
    causas: [
      {
        id: "c1",
        texto: "Capacidade instalada insuficiente na média e alta complexidade",
        subcausas: [
          { id: "c1a", texto: "Déficit de leitos de UTI fora da região metropolitana" },
          { id: "c1b", texto: "Equipamentos hospitalares obsoletos" },
        ],
      },
      {
        id: "c2",
        texto: "Fragilidade da atenção primária como porta de entrada",
        subcausas: [{ id: "c2a", texto: "Baixa cobertura de equipes de saúde da família em municípios pequenos" }],
      },
      { id: "c3", texto: "Fragmentação da regulação assistencial", subcausas: [] },
    ],
    consequencias: [
      "Agravamento de quadros clínicos evitáveis",
      "Deslocamento de pacientes para a capital",
      "Judicialização crescente do acesso",
    ],
    populacaoAfetada: "Usuários do SUS em Goiás, com maior impacto sobre a população do interior",
    objetivo: "Reduzir o tempo médio de espera por atendimento especializado e equilibrar a capacidade assistencial regional.",
    resultadoEsperado: "Tempo médio de espera reduzido em 30% até 2031, com ampliação regionalizada da capacidade.",
    indicadores: [
      { nome: "Tempo médio de espera em consulta especializada", unidade: "Dias", linhaBase: "112", meta: "78" },
      { nome: "Leitos de UTI por 10 mil habitantes", unidade: "Razão", linhaBase: "1,8", meta: "2,6" },
    ],
    orgaoCoordenador: "Secretaria de Saúde",
  },
  {
    id: "pg-infancia",
    codigo: "002",
    nome: "Primeira Infância Goiana",
    eixo: "Goiás que cuida",
    objetivoEstrategico: "Assegurar desenvolvimento integral às crianças de 0 a 6 anos.",
    problema:
      "Acesso desigual ao cuidado integral na primeira infância, com déficit de vagas em creche e acompanhamento intersetorial fragmentado.",
    evidencias: [
      "Déficit estimado de 38 mil vagas em creche pública.",
      "Somente 31% dos municípios com visitação domiciliar estruturada.",
    ],
    causas: [
      { id: "c1", texto: "Déficit de vagas em creche", subcausas: [{ id: "c1a", texto: "Insuficiência de infraestrutura em municípios de médio porte" }] },
      { id: "c2", texto: "Baixa cobertura de visitação domiciliar qualificada", subcausas: [] },
      { id: "c3", texto: "Ausência de acompanhamento intersetorial da criança", subcausas: [] },
    ],
    consequencias: ["Atraso no desenvolvimento infantil", "Evasão do cuidado em saúde", "Sobrecarga das famílias"],
    populacaoAfetada: "Crianças de 0 a 6 anos e suas famílias",
    objetivo: "Ampliar e integrar a oferta de cuidado na primeira infância.",
    resultadoEsperado: "Cobertura de cuidado integral ampliada em todas as regiões de planejamento.",
    indicadores: [{ nome: "Taxa de atendimento em creche", unidade: "Percentual", linhaBase: "39%", meta: "58%" }],
    orgaoCoordenador: "Secretaria de Educação",
  },
  {
    id: "pg-fome",
    codigo: "003",
    nome: "Goiás Sem Fome",
    eixo: "Goiás que protege",
    objetivoEstrategico: "Erradicar a insegurança alimentar grave no Estado.",
    problema:
      "Parcela significativa das famílias goianas em insegurança alimentar moderada ou grave, concentrada no Nordeste Goiano e nas periferias metropolitanas.",
    evidencias: [
      "6,4% dos domicílios em insegurança alimentar grave (PNAD 2026).",
      "Cobertura de equipamentos públicos de alimentação em apenas 22 municípios.",
    ],
    causas: [
      { id: "c1", texto: "Baixa renda e informalidade no trabalho", subcausas: [] },
      {
        id: "c2",
        texto: "Cobertura insuficiente de equipamentos públicos de alimentação",
        subcausas: [
          { id: "c2a", texto: "Ausência de restaurantes comunitários no interior" },
          { id: "c2b", texto: "Descontinuidade operacional das cozinhas comunitárias" },
        ],
      },
      { id: "c3", texto: "Fragilidade da agricultura familiar e das cadeias curtas", subcausas: [] },
      { id: "c4", texto: "Baixa articulação entre cadastro social e transferências", subcausas: [] },
    ],
    consequencias: ["Desnutrição e agravos de saúde", "Evasão escolar", "Aprofundamento da pobreza intergeracional"],
    populacaoAfetada: "Famílias em situação de insegurança alimentar",
    objetivo: "Ampliar o acesso regular a alimentação adequada e fortalecer a produção local de alimentos.",
    resultadoEsperado: "Redução da insegurança alimentar grave para menos de 3% dos domicílios até 2031.",
    indicadores: [
      { nome: "Domicílios em insegurança alimentar grave", unidade: "Percentual", linhaBase: "6,4%", meta: "2,9%" },
      { nome: "Municípios com equipamento público de alimentação", unidade: "Município", linhaBase: "22", meta: "60" },
    ],
    orgaoCoordenador: "Secretaria de Desenvolvimento Social",
  },
  {
    id: "pg-juventude",
    codigo: "004",
    nome: "Juventude, Trabalho e Renda",
    eixo: "Goiás que gera oportunidades",
    objetivoEstrategico: "Ampliar a inserção produtiva da juventude goiana.",
    problema: "Jovens de 16 a 29 anos com alta desocupação e baixa conexão entre qualificação ofertada e vagas existentes.",
    evidencias: ["Taxa de desocupação juvenil de 18,7%.", "42% dos concluintes de cursos sem inserção em 12 meses."],
    causas: [
      { id: "c1", texto: "Descompasso entre oferta de cursos e demanda das empresas", subcausas: [] },
      { id: "c2", texto: "Baixa cobertura de intermediação pública de emprego", subcausas: [] },
      { id: "c3", texto: "Dificuldade de deslocamento até os centros de qualificação", subcausas: [] },
    ],
    consequencias: ["Informalidade precoce", "Migração juvenil", "Perda de produtividade regional"],
    populacaoAfetada: "Jovens de 16 a 29 anos",
    objetivo: "Conectar qualificação, intermediação e primeiro emprego.",
    resultadoEsperado: "Elevação da taxa de inserção produtiva juvenil.",
    indicadores: [{ nome: "Taxa de desocupação juvenil", unidade: "Percentual", linhaBase: "18,7%", meta: "12,0%" }],
    orgaoCoordenador: "Secretaria de Indústria e Comércio",
  },
  {
    id: "pg-cidades",
    codigo: "005",
    nome: "Cidades Resilientes e Saneamento",
    eixo: "Goiás sustentável",
    objetivoEstrategico: "Elevar a resiliência urbana e a cobertura de saneamento.",
    problema: "Baixa capacidade municipal de resposta a eventos climáticos extremos e cobertura desigual de esgotamento sanitário.",
    evidencias: ["58 municípios com áreas de risco mapeadas sem plano de contingência."],
    causas: [
      { id: "c1", texto: "Ocupação irregular em áreas de risco", subcausas: [] },
      { id: "c2", texto: "Déficit de infraestrutura de drenagem", subcausas: [] },
      { id: "c3", texto: "Baixa capacidade técnica municipal de planejamento", subcausas: [] },
    ],
    consequencias: ["Perdas materiais recorrentes", "Doenças de veiculação hídrica"],
    populacaoAfetada: "População urbana em áreas de risco",
    objetivo: "Reduzir a vulnerabilidade urbana a eventos climáticos e ampliar o saneamento.",
    resultadoEsperado: "Cobertura de esgotamento sanitário ampliada nas regiões prioritárias.",
    indicadores: [{ nome: "Cobertura de esgotamento sanitário", unidade: "Percentual", linhaBase: "64%", meta: "80%" }],
    orgaoCoordenador: "Secretaria de Meio Ambiente",
  },
  {
    id: "pg-idoso",
    codigo: "006",
    nome: "Envelhecer com Cuidado",
    eixo: "Goiás que protege",
    objetivoEstrategico: "Ampliar a rede de cuidado à pessoa idosa.",
    problema: "Crescimento acelerado da população idosa sem rede correspondente de cuidado continuado e prevenção de violência.",
    evidencias: ["Aumento de 27% nas notificações de violência contra a pessoa idosa em cinco anos."],
    causas: [
      { id: "c1", texto: "Rede de cuidado continuado insuficiente", subcausas: [{ id: "c1a", texto: "Poucos centros-dia em funcionamento" }] },
      { id: "c2", texto: "Subnotificação de violência contra a pessoa idosa", subcausas: [] },
    ],
    consequencias: ["Institucionalização precoce", "Sobrecarga de cuidadores familiares"],
    populacaoAfetada: "Pessoas com 60 anos ou mais",
    objetivo: "Estruturar rede estadual de cuidado e proteção à pessoa idosa.",
    resultadoEsperado: "Rede de centros-dia presente em todas as regiões de planejamento.",
    indicadores: [{ nome: "Centros-dia em funcionamento", unidade: "Unidade", linhaBase: "9", meta: "28" }],
    orgaoCoordenador: "Secretaria de Desenvolvimento Social",
  },
  {
    id: "pg-regional",
    codigo: "007",
    nome: "Desenvolvimento Regional Equilibrado",
    eixo: "Goiás que gera oportunidades",
    objetivoEstrategico: "Reduzir as desigualdades econômicas entre as regiões goianas.",
    problema: "Concentração da atividade econômica no eixo metropolitano e baixa diversificação produtiva no norte e nordeste do Estado.",
    evidencias: ["PIB per capita do Nordeste Goiano equivale a 41% da média estadual."],
    causas: [
      { id: "c1", texto: "Infraestrutura logística deficiente", subcausas: [] },
      { id: "c2", texto: "Baixa diversificação produtiva regional", subcausas: [] },
    ],
    consequencias: ["Migração interna", "Dependência de transferências"],
    populacaoAfetada: "População das regiões de menor dinamismo econômico",
    objetivo: "Fomentar arranjos produtivos e infraestrutura nas regiões de menor dinamismo.",
    resultadoEsperado: "Crescimento do PIB regional acima da média estadual nas regiões prioritárias.",
    indicadores: [{ nome: "Participação das regiões prioritárias no PIB estadual", unidade: "Percentual", linhaBase: "11%", meta: "15%" }],
    orgaoCoordenador: "Secretaria de Indústria e Comércio",
  },
  {
    id: "pg-seguranca",
    codigo: "008",
    nome: "Goiás Mais Seguro",
    eixo: "Goiás que protege",
    objetivoEstrategico: "Reduzir a violência letal e fortalecer a prevenção social.",
    problema: "Concentração de crimes violentos em territórios específicos das regiões metropolitanas e do entorno do DF.",
    evidencias: ["62% dos homicídios concentrados em 18 municípios."],
    causas: [
      { id: "c1", texto: "Baixa presença de programas de prevenção social", subcausas: [] },
      { id: "c2", texto: "Fragilidade da integração entre forças de segurança", subcausas: [] },
    ],
    consequencias: ["Perda de vidas jovens", "Insegurança percebida elevada"],
    populacaoAfetada: "População residente em territórios de alta vulnerabilidade",
    objetivo: "Integrar prevenção social e ação policial nos territórios prioritários.",
    resultadoEsperado: "Redução da taxa de homicídios nos territórios prioritários.",
    indicadores: [{ nome: "Taxa de homicídios por 100 mil habitantes", unidade: "Taxa", linhaBase: "29,4", meta: "20,0" }],
    orgaoCoordenador: "Secretaria de Segurança Pública",
  },
  {
    id: "pg-cultura",
    codigo: "009",
    nome: "Cultura e Patrimônio Goiano",
    eixo: "Goiás que cuida",
    objetivoEstrategico: "Democratizar o acesso a bens culturais e preservar o patrimônio.",
    problema: "Concentração dos equipamentos culturais na capital e degradação de bens tombados no interior.",
    evidencias: ["71% dos equipamentos culturais estaduais localizados na Região Metropolitana."],
    causas: [
      { id: "c1", texto: "Baixa capilaridade dos equipamentos culturais", subcausas: [] },
      { id: "c2", texto: "Ausência de política continuada de restauro", subcausas: [] },
    ],
    consequencias: ["Perda de patrimônio histórico", "Desigualdade de acesso cultural"],
    populacaoAfetada: "População do interior e comunidades tradicionais",
    objetivo: "Ampliar a presença cultural do Estado nas regiões e preservar o patrimônio.",
    resultadoEsperado: "Rede cultural presente em todas as regiões de planejamento.",
    indicadores: [{ nome: "Municípios com equipamento cultural apoiado", unidade: "Município", linhaBase: "34", meta: "80" }],
    orgaoCoordenador: "Secretaria de Cultura",
    aptidao: "apto",
    disponibilizacao: "disponivel",
  },
  {
    id: "pg-digital",
    codigo: "010",
    nome: "Governo Digital e Transparência",
    eixo: "Goiás eficiente",
    objetivoEstrategico: "Ampliar a digitalização dos serviços públicos estaduais.",
    problema: "Serviços públicos com baixa digitalização e alto custo de atendimento presencial.",
    evidencias: ["Apenas 38% dos serviços estaduais disponíveis integralmente on-line."],
    causas: [
      { id: "c1", texto: "Sistemas legados sem integração", subcausas: [] },
      { id: "c2", texto: "Baixa maturidade digital das unidades administrativas", subcausas: [] },
    ],
    consequencias: ["Custo elevado de atendimento", "Baixa satisfação do cidadão"],
    populacaoAfetada: "Cidadãos e empresas usuários de serviços estaduais",
    objetivo: "Digitalizar e integrar os serviços públicos estaduais.",
    resultadoEsperado: "Maioria dos serviços disponível em canal digital único.",
    indicadores: [{ nome: "Serviços estaduais digitalizados", unidade: "Percentual", linhaBase: "38%", meta: "85%" }],
    orgaoCoordenador: "Secretaria de Administração",
    aptidao: "incompleto",
    disponibilizacao: "em_estruturacao",
  },
];

/** Execução financeira proveniente do SIAFIC, por Entrega. Nunca usada para desempenho físico. */
export const EXECUCAO_SIAFIC: Record<string, number> = {
  "ent-1": 9400000,
  "ent-3": 1100000,
  "ent-4": 54200000,
  "ent-6": 12800000,
  "ent-8": 7300000,
  "ent-10": 640000,
};

const mi = (n: number) => n * 1_000_000;

export const FONTES = [
  "Tesouro Estadual",
  "Convênios com a União",
  "Recursos Próprios",
  "PROTEGE",
  "Operações de Crédito",
];

/**
 * Catálogo mock de Ações Orçamentárias da LOA.
 * Regra metodológica do protótipo: uma Ação financia no máximo uma Entrega do PPA (N:1).
 */
export const ACOES: AcaoOrcamentaria[] = [
  { id: "2210", codigo: "2210", nome: "Implantação de restaurantes e cozinhas comunitárias", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2215", codigo: "2215", nome: "Operação da rede pública de alimentação", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2220", codigo: "2220", nome: "Capacitação de equipes socioassistenciais", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2230", codigo: "2230", nome: "Transferência de renda — Cartão Alimentação", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2235", codigo: "2235", nome: "Gestão do cadastro social estadual", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2240", codigo: "2240", nome: "Implantação da rede de centros-dia", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2245", codigo: "2245", nome: "Atendimento e acompanhamento continuado da pessoa idosa", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2250", codigo: "2250", nome: "Proteção à pessoa idosa em situação de violência", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2260", codigo: "2260", nome: "Inclusão produtiva da juventude", orgao: ORGAO_SETORIAL, situacao: "Ativa" },
  { id: "2310", codigo: "2310", nome: "Compra institucional da agricultura familiar", orgao: "Secretaria de Agricultura", situacao: "Ativa" },
  { id: "2315", codigo: "2315", nome: "Logística de abastecimento alimentar", orgao: "Secretaria de Agricultura", situacao: "Ativa" },
  { id: "2045", codigo: "2045", nome: "Ampliação da capacidade hospitalar", orgao: "Secretaria de Saúde", situacao: "Ativa" },
  { id: "2060", codigo: "2060", nome: "Requalificação de hospitais regionais", orgao: "Secretaria de Saúde", situacao: "Ativa" },
  { id: "2080", codigo: "2080", nome: "Aquisição de equipamentos hospitalares", orgao: "Secretaria de Saúde", situacao: "Ativa" },
  { id: "2090", codigo: "2090", nome: "Atenção especializada ambulatorial", orgao: "Secretaria de Saúde", situacao: "Ativa" },
  { id: "2410", codigo: "2410", nome: "Expansão de vagas em creche", orgao: "Secretaria de Educação", situacao: "Ativa" },
  { id: "2510", codigo: "2510", nome: "Obras de hospitais regionais", orgao: "Secretaria de Infraestrutura", situacao: "Ativa" },
];

export const PROJETOS: ProjetoGomap[] = [
  {
    id: "prj-3120",
    codigo: "GOMAP-3120",
    nome: "Rede Estadual de Restaurantes e Cozinhas Comunitárias",
    orgao: ORGAO_SETORIAL,
    situacao: "Em execução",
    fase: "Execução física",
    execucao: 42,
    cronograma: "2027–2030",
    conclusaoPrevista: "12/2030",
    ultimaAtualizacao: "08/08/2026",
    valorGlobal: mi(82.5),
  },
  {
    id: "prj-3145",
    codigo: "GOMAP-3145",
    nome: "Cartão Alimentação Goiás",
    orgao: ORGAO_SETORIAL,
    situacao: "Em execução",
    fase: "Operação continuada",
    execucao: 68,
    cronograma: "2026–2031",
    conclusaoPrevista: "12/2031",
    ultimaAtualizacao: "11/08/2026",
    valorGlobal: mi(210),
  },
  {
    id: "prj-3188",
    codigo: "GOMAP-3188",
    nome: "Logística de Abastecimento Alimentar",
    orgao: "Secretaria de Agricultura",
    situacao: "Em planejamento",
    fase: "Estruturação",
    execucao: 12,
    cronograma: "2028–2031",
    conclusaoPrevista: "12/2031",
    ultimaAtualizacao: "05/08/2026",
    valorGlobal: mi(90),
  },
  {
    id: "prj-3201",
    codigo: "GOMAP-3201",
    nome: "Qualificação de Equipes Socioassistenciais",
    orgao: ORGAO_SETORIAL,
    situacao: "Em execução",
    fase: "Execução",
    execucao: 25,
    cronograma: "2028–2029",
    conclusaoPrevista: "12/2029",
    ultimaAtualizacao: "01/08/2026",
    valorGlobal: mi(7.2),
  },
  {
    id: "prj-3260",
    codigo: "GOMAP-3260",
    nome: "Modernização do Cadastro Social Único Estadual",
    orgao: ORGAO_SETORIAL,
    situacao: "Em planejamento",
    fase: "Estudos preliminares",
    execucao: 0,
    cronograma: "2028–2030",
    conclusaoPrevista: "06/2030",
    ultimaAtualizacao: "29/07/2026",
    valorGlobal: mi(18),
  },
  {
    id: "prj-3305",
    codigo: "GOMAP-3305",
    nome: "Rede Estadual de Centros-Dia da Pessoa Idosa",
    orgao: ORGAO_SETORIAL,
    situacao: "Em execução",
    fase: "Obras",
    execucao: 33,
    cronograma: "2027–2031",
    conclusaoPrevista: "06/2031",
    ultimaAtualizacao: "10/08/2026",
    valorGlobal: mi(60),
  },
  {
    id: "prj-4010",
    codigo: "GOMAP-4010",
    nome: "Construção do Hospital Regional Norte",
    orgao: "Secretaria de Saúde",
    situacao: "Em execução",
    fase: "Obras civis",
    execucao: 38,
    cronograma: "2027–2031",
    conclusaoPrevista: "09/2031",
    ultimaAtualizacao: "12/08/2026",
    valorGlobal: mi(200),
  },
  {
    id: "prj-4020",
    codigo: "GOMAP-4020",
    nome: "Ampliação do Hospital Estadual de Urgências",
    orgao: "Secretaria de Saúde",
    situacao: "Em execução",
    fase: "Execução",
    execucao: 51,
    cronograma: "2028–2030",
    conclusaoPrevista: "12/2030",
    ultimaAtualizacao: "12/08/2026",
    valorGlobal: mi(85),
  },
];

/* ---------- IPOFs do SIAFIC ----------
 * Um IPOF possui várias parcelas. Cada parcela tem uma única Ação, uma única fonte
 * e uma classificação de despesa. Fonte e Ação pertencem à parcela, nunca ao IPOF.
 */

let seqParcela = 0;

const serie = (a: number, b: number, c: number, d: number): Record<string, number> => ({
  "2028": a,
  "2029": b,
  "2030": c,
  "2031": d,
});

/** Gera parcelas semestrais de uma Ação/fonte a partir da série anual. */
const parcelas = (acaoId: string, fonte: string, classificacao: string, vals: Record<string, number>): ParcelaIpof[] =>
  ANOS.flatMap((ano) => {
    const total = vals[ano] ?? 0;
    if (total <= 0) return [];
    const primeira = Math.round(total * 0.4);
    const partes = [
      { mes: 3, valor: primeira },
      { mes: 9, valor: total - primeira },
    ];
    return partes.map(({ mes, valor }) => {
      const base: ParcelaIpof = { id: `pc-${++seqParcela}`, acaoId, fonte, classificacao, ano, mes, valor };
      // Execução do SIAFIC disponível apenas para o primeiro exercício do plano.
      return ano === "2028"
        ? { ...base, empenhado: Math.round(valor * 0.82), liquidado: Math.round(valor * 0.7), pago: Math.round(valor * 0.63) }
        : base;
    });
  });

export const IPOFS: Ipof[] = [
  {
    id: "ip-3120-a",
    codigo: "IPOF 2028.0011",
    nome: "Obras e instalações da rede de alimentação",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3120",
    parcelas: parcelas("2210", "Tesouro Estadual", "4490.51 — Obras e instalações", serie(mi(12), mi(14), mi(10), mi(6))),
  },
  {
    id: "ip-3120-b",
    codigo: "IPOF 2028.0012",
    nome: "Custeio operacional da rede de alimentação",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3120",
    // IPOF com parcelas de duas Ações diferentes — relaciona-se a duas Entregas.
    parcelas: [
      ...parcelas("2215", "Tesouro Estadual", "3390.30 — Material de consumo", serie(mi(6), mi(7.5), mi(7.5), mi(7.5))),
      ...parcelas("2220", "PROTEGE", "3390.39 — Serviços de terceiros", serie(mi(1), mi(1), mi(1), mi(1))),
    ],
  },
  {
    id: "ip-3120-c",
    codigo: "IPOF 2028.0013",
    nome: "Equipamentos das unidades de alimentação",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3120",
    // Mesma Ação 2210 presente em outro IPOF.
    parcelas: parcelas("2210", "Convênios com a União", "4490.52 — Equipamentos", serie(mi(5), mi(5), mi(2), 0)),
  },
  {
    id: "ip-3145-a",
    codigo: "IPOF 2028.0021",
    nome: "Transferência direta às famílias",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3145",
    parcelas: parcelas("2230", "Tesouro Estadual", "3390.48 — Auxílio financeiro", serie(mi(42), mi(45), mi(46), mi(47))),
  },
  {
    id: "ip-3145-b",
    codigo: "IPOF 2028.0022",
    nome: "Gestão e operação do benefício",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3145",
    parcelas: parcelas("2235", "Recursos Próprios", "3390.39 — Serviços de terceiros", serie(mi(2), mi(2.5), mi(2.5), mi(2.5))),
  },
  {
    id: "ip-3188-a",
    codigo: "IPOF 2028.0031",
    nome: "Aquisição de alimentos da agricultura familiar",
    orgao: "Secretaria de Agricultura",
    situacao: "Ativo",
    projetoId: "prj-3188",
    // IPOF com parcelas de fontes diferentes na mesma Ação.
    parcelas: [
      ...parcelas("2310", "Convênios com a União", "3390.32 — Material distribuído", serie(mi(16), mi(16), mi(16), mi(16))),
      ...parcelas("2310", "Tesouro Estadual", "3390.32 — Material distribuído", serie(mi(2), mi(2), mi(2), mi(2))),
    ],
  },
  {
    id: "ip-3188-b",
    codigo: "IPOF 2028.0032",
    nome: "Transporte e armazenagem de alimentos",
    orgao: "Secretaria de Agricultura",
    situacao: "Ativo",
    projetoId: "prj-3188",
    parcelas: parcelas("2315", "Tesouro Estadual", "3390.33 — Transporte", serie(mi(3), mi(4), mi(4), mi(4))),
  },
  {
    id: "ip-3201-a",
    codigo: "IPOF 2028.0041",
    nome: "Formação continuada das equipes",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3201",
    parcelas: parcelas("2220", "PROTEGE", "3390.39 — Serviços de terceiros", serie(mi(2), mi(2.4), mi(1.6), mi(1.2))),
  },
  {
    id: "ip-3305-a",
    codigo: "IPOF 2028.0051",
    nome: "Implantação de centros-dia",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3305",
    parcelas: parcelas("2240", "Operações de Crédito", "4490.51 — Obras e instalações", serie(mi(9), mi(12), mi(9), mi(6))),
  },
  {
    id: "ip-3305-b",
    codigo: "IPOF 2028.0052",
    nome: "Manutenção da rede de centros-dia",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: "prj-3305",
    parcelas: parcelas("2245", "Tesouro Estadual", "3390.30 — Material de consumo", serie(mi(4), mi(4.5), mi(4.5), mi(5))),
  },
  {
    id: "ip-4010-a",
    codigo: "IPOF 2028.0101",
    nome: "Obras civis do Hospital Regional Norte",
    orgao: "Secretaria de Saúde",
    situacao: "Ativo",
    projetoId: "prj-4010",
    parcelas: parcelas("2045", "Tesouro Estadual", "4490.51 — Obras e instalações", serie(mi(20), mi(25), mi(15), mi(10))),
  },
  {
    id: "ip-4010-b",
    codigo: "IPOF 2028.0102",
    nome: "Requalificação de alas hospitalares",
    orgao: "Secretaria de Saúde",
    situacao: "Ativo",
    projetoId: "prj-4010",
    parcelas: parcelas("2060", "Tesouro Estadual", "4490.51 — Obras e instalações", serie(mi(18), mi(22), mi(20), mi(10))),
  },
  {
    id: "ip-4010-c",
    codigo: "IPOF 2028.0103",
    nome: "Equipamentos do Hospital Regional Norte",
    orgao: "Secretaria de Saúde",
    situacao: "Ativo",
    projetoId: "prj-4010",
    parcelas: parcelas("2080", "Convênios com a União", "4490.52 — Equipamentos", serie(mi(8), mi(7), mi(5), 0)),
  },
  {
    id: "ip-4020-a",
    codigo: "IPOF 2028.0111",
    nome: "Equipamentos do Hospital Estadual de Urgências",
    orgao: "Secretaria de Saúde",
    situacao: "Ativo",
    projetoId: "prj-4020",
    parcelas: parcelas("2080", "Tesouro Estadual", "4490.52 — Equipamentos", serie(mi(10), mi(10), mi(5), mi(5))),
  },
  {
    id: "ip-av-1",
    codigo: "IPOF 2028.0201",
    nome: "Manutenção da rede socioassistencial (atividade continuada)",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2245", "Tesouro Estadual", "3390.30 — Material de consumo", serie(mi(6), mi(6), mi(6), mi(6))),
  },
  {
    id: "ip-av-2",
    codigo: "IPOF 2028.0202",
    nome: "Serviços de apoio à gestão social (atividade continuada)",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2235", "Recursos Próprios", "3390.39 — Serviços de terceiros", serie(mi(2.5), mi(3), mi(3), mi(3))),
  },
  {
    id: "ip-av-3",
    codigo: "IPOF 2028.0203",
    nome: "Aquisição de gêneros alimentícios (processo continuado)",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2215", "PROTEGE", "3390.32 — Material distribuído", serie(mi(4), mi(5), mi(4.5), mi(4.5))),
  },
  {
    id: "ip-av-4",
    codigo: "IPOF 2028.0204",
    nome: "Custeio da atenção especializada",
    orgao: "Secretaria de Saúde",
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2090", "Convênios com a União", "3390.39 — Serviços de terceiros", serie(mi(21), mi(23), mi(24), mi(24))),
  },
  {
    id: "ip-av-5",
    codigo: "IPOF 2028.0205",
    nome: "Manutenção da rede escolar",
    orgao: "Secretaria de Educação",
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2410", "Tesouro Estadual", "3390.30 — Material de consumo", serie(mi(10), mi(11), mi(12), mi(12))),
  },
  {
    id: "ip-av-6",
    codigo: "IPOF 2028.0206",
    nome: "Ampliação de equipamentos socioassistenciais",
    orgao: ORGAO_SETORIAL,
    situacao: "Ativo",
    projetoId: null,
    parcelas: parcelas("2240", "Operações de Crédito", "4490.61 — Aquisição de imóveis", serie(mi(6), mi(9), mi(9), mi(6))),
  },
];

const meta = (a?: number | null, b?: number | null, c?: number | null, d?: number | null) => ({
  "2028": a ?? null,
  "2029": b ?? null,
  "2030": c ?? null,
  "2031": d ?? null,
});

const SEDS = ORGAO_SETORIAL;

const iniciativas: Iniciativa[] = [
  {
    id: "ini-1",
    programaId: "pg-fome",
    orgao: SEDS,
    nome: "Ampliação da rede pública de alimentação",
    descricao: "Expandir e qualificar restaurantes e cozinhas comunitárias nos territórios de maior insegurança alimentar.",
    publicoAlvo: "Famílias em insegurança alimentar moderada ou grave",
    causas: ["c2", "c2a"],
    status: "em_preenchimento",
    atualizadoEm: "12/08/2026",
    versao: 1,
    unidadeResponsavel: "Superintendência de Segurança Alimentar",
    resultadoEsperado:
      "Rede pública de alimentação presente nos 20 municípios de maior insegurança alimentar, com oferta regular de refeições.",
    indicadores: [
      {
        id: "iin-1",
        nome: "Cobertura municipal da rede pública de alimentação",
        descricao: "Proporção dos municípios prioritários com equipamento público de alimentação em operação.",
        unidade: "Percentual",
        formula: "(municípios prioritários com equipamento / municípios prioritários) x 100",
        fonte: "Cadastro estadual de equipamentos de alimentação",
        periodicidade: "Semestral",
        valorReferencia: "34%",
        anoReferencia: "2026",
        polaridade: "maior_melhor",
        metas: { "2028": "48%", "2029": "60%", "2030": "72%", "2031": "85%" },
      },
      {
        id: "iin-2",
        nome: "Refeições subsidiadas por habitante em insegurança alimentar",
        descricao: "Volume anual de refeições servidas em relação ao público estimado.",
        unidade: "Razão",
        formula: "refeições servidas / público estimado",
        fonte: "Relatório operacional da rede",
        periodicidade: "Anual",
        valorReferencia: "11,2",
        anoReferencia: "2026",
        polaridade: "maior_melhor",
        metas: { "2028": "14,0", "2029": "16,5", "2030": "18,0", "2031": "20,0" },
      },
    ],
  },
  {
    id: "ini-2",
    programaId: "pg-fome",
    orgao: SEDS,
    nome: "Transferência de renda para segurança alimentar",
    descricao: "Operação e ampliação do Cartão Alimentação Goiás com integração ao cadastro social.",
    publicoAlvo: "Famílias inscritas no cadastro social estadual",
    causas: ["c1", "c4"],
    status: "em_analise",
    atualizadoEm: "11/08/2026",
    enviadoEm: "10/08/2026",
    analista: "Maria Fonseca",
    versao: 2,
    unidadeResponsavel: "Superintendência de Transferência de Renda",
    resultadoEsperado: "Famílias em insegurança alimentar grave com transferência regular e cadastro atualizado.",
    indicadores: [
      {
        id: "iin-3",
        nome: "Famílias elegíveis com benefício ativo",
        descricao: "Proporção das famílias elegíveis efetivamente atendidas.",
        unidade: "Percentual",
        formula: "(famílias com benefício ativo / famílias elegíveis) x 100",
        fonte: "Cadastro social estadual",
        periodicidade: "Trimestral",
        valorReferencia: "68%",
        anoReferencia: "2026",
        polaridade: "maior_melhor",
        metas: { "2028": "80%", "2029": "85%", "2030": "90%", "2031": "92%" },
      },
    ],
  },
  {
    id: "ini-3",
    programaId: "pg-fome",
    orgao: SEDS,
    nome: "Fortalecimento das cadeias curtas de alimentos",
    descricao: "Compra institucional da agricultura familiar e logística de abastecimento nos territórios prioritários.",
    publicoAlvo: "Agricultores familiares e equipamentos públicos de alimentação",
    causas: ["c3"],
    status: "devolvida",
    atualizadoEm: "10/08/2026",
    enviadoEm: "07/08/2026",
    analista: "Maria Fonseca",
    versao: 2,
  },
  {
    id: "ini-4",
    programaId: "pg-idoso",
    orgao: SEDS,
    nome: "Implantação da rede de centros-dia",
    descricao: "Implantar centros-dia regionais para cuidado continuado da pessoa idosa.",
    publicoAlvo: "Pessoas idosas com dependência leve e moderada",
    causas: ["c1", "c1a"],
    status: "validada",
    atualizadoEm: "04/08/2026",
    enviadoEm: "28/07/2026",
    analista: "João Peixoto",
    versao: 1,
    unidadeResponsavel: "Superintendência da Pessoa Idosa",
    resultadoEsperado: "Cuidado continuado disponível em todas as regiões de planejamento até 2031.",
    indicadores: [
      {
        id: "iin-4",
        nome: "Regiões com centro-dia em operação",
        descricao: "Regiões de planejamento cobertas por ao menos um centro-dia.",
        unidade: "Unidade",
        formula: "contagem de regiões cobertas",
        fonte: "Rede socioassistencial estadual",
        periodicidade: "Semestral",
        valorReferencia: "3",
        anoReferencia: "2026",
        polaridade: "maior_melhor",
        metas: { "2028": "4", "2029": "5", "2030": "6", "2031": "7" },
      },
    ],
  },
  {
    id: "ini-5",
    programaId: "pg-idoso",
    orgao: SEDS,
    nome: "Enfrentamento à violência contra a pessoa idosa",
    descricao: "Qualificação da rede socioassistencial para notificação e acolhimento.",
    publicoAlvo: "Pessoas idosas em situação de violência",
    causas: ["c2"],
    status: "enviada",
    atualizadoEm: "09/08/2026",
    enviadoEm: "09/08/2026",
    versao: 1,
  },
  {
    id: "ini-6",
    programaId: "pg-juventude",
    orgao: SEDS,
    nome: "Inclusão produtiva de jovens do cadastro social",
    descricao: "Encaminhamento de jovens beneficiários de programas sociais a cursos e vagas de primeiro emprego.",
    publicoAlvo: "Jovens de 16 a 29 anos inscritos no cadastro social",
    causas: ["c2"],
    status: "em_preenchimento",
    atualizadoEm: "12/08/2026",
    versao: 1,
  },
  // Outros órgãos — visíveis apenas na Área Central
  {
    id: "ini-7",
    programaId: "pg-saude",
    orgao: "Secretaria de Saúde",
    nome: "Ampliação da capacidade assistencial",
    descricao: "Ampliação de leitos de UTI e requalificação de hospitais regionais.",
    publicoAlvo: "Usuários do SUS",
    causas: ["c1", "c1a"],
    status: "em_analise",
    atualizadoEm: "12/08/2026",
    enviadoEm: "11/08/2026",
    analista: "Maria Fonseca",
    versao: 1,
  },
  {
    id: "ini-8",
    programaId: "pg-saude",
    orgao: "Secretaria de Saúde",
    nome: "Fortalecimento da atenção especializada",
    descricao: "Ampliação da oferta de consultas e exames especializados regionalizados.",
    publicoAlvo: "Usuários em fila de regulação",
    causas: ["c3"],
    status: "validada",
    atualizadoEm: "10/08/2026",
    enviadoEm: "02/08/2026",
    analista: "João Peixoto",
    versao: 1,
  },
  {
    id: "ini-9",
    programaId: "pg-saude",
    orgao: "Secretaria de Infraestrutura",
    nome: "Obras de hospitais regionais",
    descricao: "Execução das obras civis dos hospitais regionais de Formosa e Uruaçu.",
    publicoAlvo: "População das regiões Nordeste e Norte",
    causas: ["c1"],
    status: "enviada",
    atualizadoEm: "09/08/2026",
    enviadoEm: "09/08/2026",
    versao: 1,
  },
  {
    id: "ini-10",
    programaId: "pg-fome",
    orgao: "Secretaria de Agricultura",
    nome: "Compra institucional da agricultura familiar",
    descricao: "Aquisição de alimentos da agricultura familiar para equipamentos públicos.",
    publicoAlvo: "Agricultores familiares",
    causas: ["c3"],
    status: "validada",
    atualizadoEm: "06/08/2026",
    enviadoEm: "30/07/2026",
    analista: "João Peixoto",
    versao: 1,
  },
  {
    id: "ini-11",
    programaId: "pg-infancia",
    orgao: "Secretaria de Educação",
    nome: "Expansão da rede de creches",
    descricao: "Cofinanciamento da ampliação de vagas em creche em municípios de médio porte.",
    publicoAlvo: "Crianças de 0 a 3 anos",
    causas: ["c1", "c1a"],
    status: "em_analise",
    atualizadoEm: "12/08/2026",
    enviadoEm: "10/08/2026",
    analista: "Maria Fonseca",
    versao: 1,
  },
  {
    id: "ini-12",
    programaId: "pg-infancia",
    orgao: "Secretaria de Saúde",
    nome: "Visitação domiciliar na primeira infância",
    descricao: "Implantação de programa estadual de visitação domiciliar qualificada.",
    publicoAlvo: "Gestantes e crianças de 0 a 3 anos",
    causas: ["c2"],
    status: "devolvida",
    atualizadoEm: "11/08/2026",
    enviadoEm: "05/08/2026",
    analista: "Maria Fonseca",
    versao: 2,
  },
];

const entregas: Entrega[] = [
  {
    id: "ent-1",
    iniciativaId: "ini-1",
    nome: "Restaurantes comunitários em funcionamento",
    descricao: "Novas unidades entregues e operando com no mínimo 300 refeições/dia.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Termo de inauguração e relatório mensal de operação",
    comportamentoSugerido: "acumulativa",
    comportamento: "acumulativa",
    comportamentoValidado: true,
    metas: meta(6, 8, null, 12),
    territorio: { tipo: "territorializavel", regioes: ["Nordeste Goiano", "Entorno do DF", "Metropolitana de Goiânia"] },
    gomap: "sim",
  },
  {
    id: "ent-2",
    iniciativaId: "ini-1",
    nome: "Refeições servidas pela rede pública",
    descricao: "Refeições subsidiadas servidas anualmente na rede estadual.",
    unidadeMedida: "Refeição servida",
    metodoComprovacao: "",
    comportamentoSugerido: "fluxo",
    comportamentoValidado: false,
    metas: meta(null, null, null, null),
    territorio: { tipo: null, regioes: [] },
    gomap: "depois",
  },
  {
    id: "ent-3",
    iniciativaId: "ini-1",
    nome: "Equipes de cozinhas comunitárias capacitadas",
    descricao: "Profissionais capacitados em manipulação de alimentos e gestão da unidade.",
    unidadeMedida: "Profissional capacitado",
    metodoComprovacao: "Lista de presença e certificação",
    comportamentoSugerido: "fluxo",
    comportamento: "fluxo",
    comportamentoValidado: true,
    metas: meta(120, 150, 150, 0),
    territorio: { tipo: "nao_territorializavel", regioes: [] },
    gomap: "sim",
  },
  {
    id: "ent-4",
    iniciativaId: "ini-2",
    nome: "Famílias beneficiárias do Cartão Alimentação",
    descricao: "Famílias com benefício ativo no exercício.",
    unidadeMedida: "Pessoa atendida",
    metodoComprovacao: "Folha de pagamento do benefício",
    comportamentoSugerido: "estoque",
    comportamento: "estoque",
    comportamentoValidado: true,
    metas: meta(120000, 135000, 140000, 140000),
    territorio: { tipo: "estadual", regioes: [] },
    gomap: "sim",
  },
  {
    id: "ent-5",
    iniciativaId: "ini-2",
    nome: "Integração do cadastro social ao pagamento do benefício",
    descricao: "Marco de integração entre o cadastro estadual e o operador financeiro.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Termo de homologação do sistema",
    comportamentoSugerido: "marco",
    comportamento: "marco",
    comportamentoValidado: true,
    metas: meta(1, 0, 0, 0),
    territorio: { tipo: "nao_territorializavel", regioes: [] },
    gomap: "nao",
  },
  {
    id: "ent-6",
    iniciativaId: "ini-3",
    nome: "Alimentos adquiridos da agricultura familiar",
    descricao: "Volume anual adquirido por compra institucional.",
    unidadeMedida: "Tonelada",
    metodoComprovacao: "Notas fiscais de aquisição",
    comportamentoSugerido: "fluxo",
    comportamento: "fluxo",
    comportamentoValidado: true,
    metas: meta(4200, 5000, 5600, 6000),
    territorio: { tipo: "territorializavel", regioes: ["Sudoeste Goiano", "Centro Goiano"] },
    gomap: "sim",
  },
  {
    id: "ent-7",
    iniciativaId: "ini-3",
    nome: "Municípios com cadeia curta estruturada",
    descricao: "Municípios com feiras e centrais de abastecimento apoiadas.",
    unidadeMedida: "Município atendido",
    metodoComprovacao: "Termo de adesão municipal",
    comportamentoSugerido: "acumulativa",
    comportamentoValidado: false,
    metas: meta(8, null, 14, 18),
    territorio: { tipo: "territorializavel", regioes: [] },
    gomap: "nao",
  },
  {
    id: "ent-8",
    iniciativaId: "ini-4",
    nome: "Centros-dia implantados",
    descricao: "Unidades regionais em funcionamento.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Ato de inauguração",
    comportamentoSugerido: "acumulativa",
    comportamento: "acumulativa",
    comportamentoValidado: true,
    metas: meta(4, 6, 5, 4),
    territorio: { tipo: "territorializavel", regioes: ["Norte Goiano", "Sul Goiano", "Metropolitana de Goiânia"] },
    gomap: "sim",
  },
  {
    id: "ent-9",
    iniciativaId: "ini-4",
    nome: "Pessoas idosas atendidas em cuidado continuado",
    descricao: "Atendimentos continuados registrados na rede.",
    unidadeMedida: "Pessoa atendida",
    metodoComprovacao: "Registro no sistema socioassistencial",
    comportamentoSugerido: "estoque",
    comportamento: "estoque",
    comportamentoValidado: true,
    metas: meta(1800, 2600, 3200, 3800),
    territorio: { tipo: "estadual", regioes: [] },
    gomap: "nao",
  },
  {
    id: "ent-10",
    iniciativaId: "ini-5",
    nome: "Equipes socioassistenciais qualificadas em proteção à pessoa idosa",
    descricao: "Profissionais capacitados na rede municipal e estadual.",
    unidadeMedida: "Profissional capacitado",
    metodoComprovacao: "Certificados emitidos",
    comportamentoSugerido: "fluxo",
    comportamento: "fluxo",
    comportamentoValidado: true,
    metas: meta(400, 400, 400, 400),
    territorio: { tipo: "estadual", regioes: [] },
    gomap: "sim",
  },
  {
    id: "ent-11",
    iniciativaId: "ini-6",
    nome: "Jovens encaminhados a vagas de primeiro emprego",
    descricao: "Encaminhamentos efetivados pela rede socioassistencial.",
    unidadeMedida: "Pessoa atendida",
    metodoComprovacao: "",
    comportamentoSugerido: "fluxo",
    comportamentoValidado: false,
    metas: meta(null, null, null, null),
    territorio: { tipo: null, regioes: [] },
    gomap: null,
  },
  {
    id: "ent-12",
    iniciativaId: "ini-7",
    nome: "Leitos de UTI acrescentados",
    descricao: "Novos leitos habilitados nas macrorregiões deficitárias.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Habilitação ministerial",
    comportamentoSugerido: "acumulativa",
    comportamento: "acumulativa",
    comportamentoValidado: true,
    metas: meta(60, 80, 60, 40),
    territorio: { tipo: "territorializavel", regioes: ["Norte Goiano", "Nordeste Goiano", "Sudoeste Goiano"] },
    gomap: "nao",
  },
  {
    id: "ent-13",
    iniciativaId: "ini-7",
    nome: "Hospitais regionais requalificados",
    descricao: "Unidades com obras e equipamentos concluídos.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Termo de recebimento definitivo",
    comportamentoSugerido: "acumulativa",
    comportamento: "acumulativa",
    comportamentoValidado: true,
    metas: meta(1, 2, 1, 1),
    territorio: { tipo: "territorializavel", regioes: ["Nordeste Goiano", "Norte Goiano"] },
    gomap: "nao",
  },
  {
    id: "ent-14",
    iniciativaId: "ini-11",
    nome: "Vagas em creche cofinanciadas",
    descricao: "Novas vagas em funcionamento com cofinanciamento estadual.",
    unidadeMedida: "Unidade",
    metodoComprovacao: "Censo escolar",
    comportamentoSugerido: "acumulativa",
    comportamento: "acumulativa",
    comportamentoValidado: true,
    metas: meta(6000, 8000, 9000, 9000),
    territorio: { tipo: "territorializavel", regioes: ["Entorno do DF", "Sul Goiano"] },
    gomap: "nao",
  },
  {
    id: "ent-15",
    iniciativaId: "ini-12",
    nome: "Municípios com visitação domiciliar implantada",
    descricao: "Municípios com equipes formadas e programa em operação.",
    unidadeMedida: "Município atendido",
    metodoComprovacao: "Termo de adesão",
    comportamentoSugerido: "acumulativa",
    comportamentoValidado: false,
    metas: meta(20, null, 40, 50),
    territorio: { tipo: "territorializavel", regioes: [] },
    gomap: "depois",
  },
];

const vinculos: Vinculo[] = [
  { id: "v-1", entregaId: "ent-1", projetoId: "prj-3120" },
  { id: "v-2", entregaId: "ent-1", projetoId: "prj-3260" },
  { id: "v-3", entregaId: "ent-3", projetoId: "prj-3120" },
  { id: "v-4", entregaId: "ent-3", projetoId: "prj-3201" },
  { id: "v-5", entregaId: "ent-4", projetoId: "prj-3145" },
  { id: "v-6", entregaId: "ent-6", projetoId: "prj-3188" },
  { id: "v-7", entregaId: "ent-8", projetoId: "prj-3305" },
  { id: "v-8", entregaId: "ent-10", projetoId: "prj-3201" },
  { id: "v-9", entregaId: "ent-12", projetoId: "prj-4010" },
  { id: "v-10", entregaId: "ent-12", projetoId: "prj-4020" },
  { id: "v-11", entregaId: "ent-13", projetoId: "prj-4010" },
];

const vinculoAcao = (id: string, entregaId: string, acaoId: string): VinculoAcao => ({ id, entregaId, acaoId });

/**
 * Vinculação orçamentária Entrega × Ação (N:1). O financeiro da Entrega é derivado
 * automaticamente das parcelas dos IPOFs de cada Ação — não há apropriação manual.
 *
 * Cenários demonstrativos:
 *  A) ent-1  — 2 Projetos GOMAP + 1 Ação presente em 2 IPOFs (fontes diferentes).
 *  B) ent-9  — nenhum Projeto, Ação continuada com IPOF de Projeto e IPOF avulso.
 *  C) ent-6  — 1 Projeto + 2 Ações, uma delas com duas fontes no mesmo IPOF.
 *  D) ent-10 — Projeto associado, sem nenhuma Ação vinculada (sem financeiro).
 *  E) ent-12 — 2 Ações, 2 Projetos distintos financiando a mesma Entrega.
 */
const vinculosAcao: VinculoAcao[] = [
  vinculoAcao("va-1", "ent-1", "2210"),
  vinculoAcao("va-2", "ent-2", "2215"),
  vinculoAcao("va-3", "ent-3", "2220"),
  vinculoAcao("va-4", "ent-4", "2230"),
  vinculoAcao("va-5", "ent-5", "2235"),
  vinculoAcao("va-6", "ent-6", "2310"),
  vinculoAcao("va-7", "ent-6", "2315"),
  vinculoAcao("va-8", "ent-8", "2240"),
  vinculoAcao("va-9", "ent-9", "2245"),
  vinculoAcao("va-10", "ent-12", "2045"),
  vinculoAcao("va-11", "ent-12", "2080"),
  vinculoAcao("va-12", "ent-13", "2060"),
  vinculoAcao("va-13", "ent-14", "2410"),
];


const comentarios: Comentario[] = [
  {
    id: "cm-1",
    alvoTipo: "entrega",
    alvoId: "ent-7",
    campo: "metas",
    texto: "A meta de 2029 não foi informada. Se a intenção é não haver execução no ano, informe 0 explicitamente.",
    autor: "Maria Fonseca",
    criadoEm: "10/08/2026",
    resolvido: false,
  },
  {
    id: "cm-2",
    alvoTipo: "entrega",
    alvoId: "ent-7",
    campo: "territorio",
    texto: "A Entrega foi classificada como territorializável, mas nenhuma região foi indicada.",
    autor: "Maria Fonseca",
    criadoEm: "10/08/2026",
    resolvido: false,
  },
  {
    id: "cm-3",
    alvoTipo: "iniciativa",
    alvoId: "ini-3",
    campo: "causas",
    texto: "Relacionar também a causa de baixa articulação entre cadastro e programas, dado o público informado.",
    autor: "Maria Fonseca",
    criadoEm: "10/08/2026",
    resolvido: false,
  },
  {
    id: "cm-4",
    alvoTipo: "entrega",
    alvoId: "ent-15",
    campo: "metas",
    texto: "Meta de 2029 ausente na série.",
    autor: "Maria Fonseca",
    criadoEm: "11/08/2026",
    resolvido: false,
  },
];

const eventos: Evento[] = [
  { id: "ev-1", iniciativaId: "ini-3", quando: "07/08/2026", autor: ORGAO_SETORIAL, texto: "Iniciativa enviada para análise (versão 1)" },
  { id: "ev-2", iniciativaId: "ini-3", quando: "08/08/2026", autor: "Maria Fonseca", texto: "Análise iniciada pela Área Central" },
  { id: "ev-3", iniciativaId: "ini-3", quando: "10/08/2026", autor: "Maria Fonseca", texto: "Iniciativa devolvida para ajuste com 3 apontamentos" },
  { id: "ev-4", iniciativaId: "ini-2", quando: "10/08/2026", autor: ORGAO_SETORIAL, texto: "Iniciativa enviada para análise (versão 2)" },
  { id: "ev-5", iniciativaId: "ini-2", quando: "11/08/2026", autor: "Maria Fonseca", texto: "Análise iniciada pela Área Central" },
  { id: "ev-6", iniciativaId: "ini-4", quando: "28/07/2026", autor: ORGAO_SETORIAL, texto: "Iniciativa enviada para análise (versão 1)" },
  { id: "ev-7", iniciativaId: "ini-4", quando: "04/08/2026", autor: "João Peixoto", texto: "Iniciativa validada" },
  { id: "ev-8", iniciativaId: "ini-5", quando: "09/08/2026", autor: ORGAO_SETORIAL, texto: "Iniciativa enviada para análise (versão 1)" },
];

export function estadoInicial(): PpaState {
  return {
    orgaoAtual: SEDS,
    usuario: "Vagner Ribeiro",
    analista: "Maria Fonseca",
    programas: PROGRAMAS.map((p) => ({
      aptidao: "apto" as const,
      disponibilizacao: "disponivel" as const,
      ...p,
    })),
    semContribuicao: [
      { programaId: "pg-cidades", orgao: SEDS },
      { programaId: "pg-seguranca", orgao: "Secretaria de Educação" },
    ],
    iniciativas,
    entregas,
    vinculos,
    vinculosAcao,
    comentarios,
    eventos,
  };
}
